version: "3"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - '5433:5432'
  graphql-skeleton:
    build: .
    container_name: graphql-skeleton-api
    ports:
      - '5000:5000'
volumes:
  db-data: